### ISSUE TITLE
Sophia can you compile the latest version, type something, and send me the LogCat?

### ISSUE THREAD

**Issue by GittyupMule** [GittyupMule/arromaniyyah#4]

**Comment by GittyupMule** [comment]
I believe I may have fixed the error, can you check?

**Comment by saquil2** [comment]
<img width="207" alt="capture" src="https://user-images.githubusercontent.com/42951187/49349719-894c0c80-f671-11e8-8599-50b50eb65b87.PNG">
Here's what I see when I run the latest version.

**Comment by GittyupMule** [comment]
I believe I have the `BroadcastReceiver` logic working, can you check?

**Comment by GittyupMule** [comment]
That is, when your laptop is charged

**Comment by saquil2** [comment]
When I run it just looks the same as it did at office hours. 
![image](https://user-images.githubusercontent.com/42951187/49397065-3d947400-f700-11e8-80ce-2f1af342102b.png)

**Comment by GittyupMule** [comment]
Can you send me the logcat?

**Comment by saquil2** [comment]
[logcat2.txt](https://github.com/GittyupMule/arromaniyyah/files/2641024/logcat2.txt)
